### ISSUE TITLE
Fix webhook_url => github_webhook_url

### ISSUE THREAD

**Issue by osterman** [cloudposse/terraform-github-repository-webhooks#3]
## what
* `webhook_url` is wrong variable and should be `github_webhook_url`

## why

* #2 fixed this but the change was lost

**Comment by osterman** [comment]
@joshmyers can you help us fix `webhook_content_type` as well. The example is wrong.

**Comment by aknysh** [comment]
the example was fixed in https://github.com/cloudposse/terraform-github-repository-webhooks/pull/9
