### ISSUE TITLE
GitHub provider not supported on arm64 macs (M1)

### ISSUE THREAD

**Issue by mihaiplesa** [cloudposse/terraform-github-repository-webhooks#34]
```
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/hashicorp/github v3.0.0 does not have a
│ package available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all
│ providers are available for all platforms. Other versions of this provider
│ may have different platforms supported.
```

**Comment by johnB96** [comment]
This fork with this change is working, the changes are fairly trivial https://github.com/sonatype/terraform-github-repository-webhooks/commit/375f3b5f62d21c227e2c19ae9e274dfedfbeb8e5

**Comment by kevcube** [comment]
@johnB96 see discussion in #35

The SweetOps slack is a good place to ask about this.

My solution currently is running `terraform` inside of a docker container, because linux_arm64 has support for `hashicorp/template` and `hashicorp/github 3.0`
