### ISSUE TITLE
application/json is invalid default value for webhook_content_type

### ISSUE THREAD

**Issue by joppa27** [cloudposse/terraform-github-repository-webhooks#4]
### what

- `application/json` is an incorrect default value to use for the `webhook_content_type` variable

### why

- The only supported values for `content_type` in the github api are `json` & `form`
  https://developer.github.com/v3/repos/hooks/#parameters  
  ![image](https://user-images.githubusercontent.com/11927879/49884454-e29b0500-fe02-11e8-88d9-146cdc06dff9.png)

**Comment by joppa27** [comment]
interesting side effect of this, because [stricter api validation](https://developer.github.com/changes/2018-11-07-strict-validation/) was postponed, after a successful `terraform apply` the webhook UI looks like this:
![image](https://user-images.githubusercontent.com/11927879/49885082-5d185480-fe04-11e8-9ca8-7ba6041fa56b.png)
but the `content-type` of the request header is still `form`
```
Request URL: https://this-is-my-webhook.com
Request method: POST
**content-type: application/x-www-form-urlencoded**
Expect: 
User-Agent: GitHub-Hookshot/c123456
X-GitHub-Delivery: b331234-fe20-132431e8-950c-7659d1f5ba07b
X-GitHub-Event: ping
```

**Comment by osterman** [comment]
Oh wow, that's tricky!
